---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python:3.6-alpine

params:
  SRC_PATH: .

inputs:
- name: repo

outputs:
- name: test-result

run:
  path: sh
  args:
  - repo/ci/tasks/python/test.sh
