---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: hseeberger/scala-sbt
inputs:
  - name: repo
outputs:
  - name: test-result
run:
  path: /bin/bash
  args:
    - repo/ci/tasks/sbt/sbt-assembly.sh
caches:
  - path: .ivy2
