---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: hseeberger/scala-sbt

params:
  SRC_PATH: .

inputs:
  - name: repo
  - name: version

outputs:
  - name: artifact

run:
  path: /bin/bash
  args:
    - repo/ci/tasks/sbt/sbt-assembly.sh

caches:
  - path: .ivy2
