---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: hseeberger/scala-sbt

params:
  SRC_PATH: .
  PROJECT:

inputs:
  - name: repo

outputs:
  - name: test-result

run:
  path: /bin/bash
  args:
    - repo/ci/tasks/sbt/test.sh

caches:
  - path: .ivy2
