groups: []
resources:
- name: hawkeye-repo
  type: git
  source:
    check_every: 30s
    paths:
    - katana/*
    - project/*
    - build.sbt
    private_key: ((github-private-key))
    uri: git@github.com:paufregi/hawkeye.git
- name: pull-request
  type: pull-request
  source:
    access_token: ((github-access-token))
    every: true
    paths:
    - katana/*
    - project/*
    - build.sbt
    private_key: ((github-private-key))
    repo: paufregi/hawkeye
- name: version
  type: semver
  source:
    access_key_id: ((aws-access-key-id))
    bucket: mm-shark
    initial_version: 0.0.0
    key: hawkeye/katana/version
    region_name: us-east-1
    secret_access_key: ((aws-secret-access-key))
- name: concourse-tasks
  type: git
  source:
    private_key: ((github-private-key))
    uri: git@github.com:movio/concourse-tasks.git
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
jobs:
- name: verify
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: pull-request
    params:
      context: katana/scala
      path: pull-request
      status: pending
  - aggregate:
    - task: sbt-test
      file: pull-request/ci/tasks/sbt/test.yml
      params:
        PROJECT: katana
      input_mapping:
        repo: pull-request
    - task: sbt-it-test
      file: pull-request/ci/tasks/sbt/it-test.yml
      params:
        PROJECT: katana
      input_mapping:
        repo: pull-request
  on_failure:
    put: pull-request
    params:
      context: katana/scala
      path: pull-request
      status: failure
  on_success:
    put: pull-request
    params:
      context: katana/scala
      path: pull-request
      status: success
- name: bump-version
  serial: true
  plan:
  - aggregate:
    - get: hawkeye-repo
      trigger: true
    - get: version
    - get: concourse-tasks
  - task: bump-version
    file: concourse-tasks/version/tasks/bump-version.yaml
    params:
      VERSION_PATH: katana/version
    input_mapping:
      repo: hawkeye-repo
      tasks: concourse-tasks
  - put: version
    params:
      file: new-version/version
- name: build-image
  serial: true
  plan:
  - aggregate:
    - get: hawkeye-repo
      passed:
      - bump-version
    - get: version
      passed:
      - bump-version
      trigger: true
  - task: sbt-assembly
    file: hawkeye-repo/ci/tasks/sbt/assembly.yml
    params:
      PROJECT: katana
    input_mapping:
      repo: hawkeye-repo
  - task: prepare-docker
    file: hawkeye-repo/ci/tasks/docker/prepare.yml
    params:
      DOCKERFILE_PATH: katana/docker/Dockerfile
      NAME: katana
    input_mapping:
      repo: hawkeye-repo
- name: deploy-dev
  serial: true
  plan:
  - aggregate:
    - get: hawkeye-repo
      passed:
      - build-image
    - get: version
      passed:
      - build-image
      trigger: true
  - task: deploy
    file: hawkeye-repo/ci/tasks/kube/apply.yml
    params:
      TEMPLATE: katana/kube/kube.yml.tmpl
    input_mapping:
      repo: hawkeye-repo
- name: deploy-us-prod
  serial: true
  plan:
  - aggregate:
    - get: hawkeye-repo
      passed:
      - deploy-dev
    - get: version
      passed:
      - deploy-dev
  - task: deploy
    file: hawkeye-repo/ci/tasks/kube/apply.yml
    params:
      TEMPLATE: katana/kube/kube.yml.tmpl
    input_mapping:
      repo: hawkeye-repo
