resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: hawkeye-repo
  type: git
  source:
    uri: git@github.com:paufregi/hawkeye.git
    private_key: ((github-private-key))
    check_every: 30s
    paths:
    - clint/*
    - project/*
    - build.sbt
    - ci/*
- name: pull-request
  type: pull-request
  source:
    repo: paufregi/hawkeye
    access_token: ((github-access-token))
    private_key: ((github-private-key))
    every: true
    paths:
    - clint/*
    - project/*
    - build.sbt
- name: version
  type: semver
  source:
    region_name: us-east-1
    bucket: mm-shark
    key: hawkeye/clint/version
    initial_version: 0.0.0
    access_key_id: ((aws-access-key-id))
    secret_access_key: ((aws-secret-access-key))
- name: concourse-tasks
  type: git
  source:
    uri: git@github.com:movio/concourse-tasks.git
    private_key: ((github-private-key))
- name: jar-artifact
  type: s3
  source:
    region_name: us-east-1
    bucket: mm-shark
    regexp: hawkeye/clint/clint-(\d+\.\d+\.\d+)
    access_key_id: ((aws-access-key-id))
    secret_access_key: ((aws-secret-access-key))

jobs:
- name: verify
  plan:
  - aggregate:
    - get: pull-request
      trigger: true
      version: every
      params:
        fetch_merge: true
  - put: pull-request
    params:
      path: pull-request
      status: pending
  - task: sbt-test
    file: pull-request/ci/tasks/sbt/test.yml
    input_mapping:
      repo: pull-request
    on_success:
      put: pull-request
      params:
        path: pull-request
        status: success
    on_failure:
      put: pull-request
      params:
        path: pull-request
        status: failure
- name: bump-version
  serial: true
  plan:
  - aggregate:
    - get: hawkeye-repo
      trigger: true
    - get: version
    - get: concourse-tasks
  - task: bump-version
    file: concourse-tasks/version/tasks/bump-version.yaml
    input_mapping:
      tasks: concourse-tasks
      repo: hawkeye-repo
    params:
      VERSION_PATH: clint/version
  - put: version
    params:
      file: new-version/version
- name: release-jar
  serial: true
  plan:
  - aggregate:
    - get: hawkeye-repo
      passed: [bump-version]
    - get: version
      passed: [bump-version]
      trigger: true
  - task: sbt-assembly
    file: hawkeye-repo/ci/tasks/sbt/assembly.yml
    input_mapping:
      repo: hawkeye-repo
  - put: jar-artifact
    params:
      file: artifact/clint-*
