resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: pull-request-scala
  type: pull-request
  source:
    repo: paufregi/hawkeye
    access_token: ((github-access-token))
    private_key: ((github-private-key))
    every: true
    paths:
    - archery/arrow/*
    - project/*
    - build.sbt
- name: pull-request-python
  type: pull-request
  source:
    repo: paufregi/hawkeye
    access_token: ((github-access-token))
    private_key: ((github-private-key))
    every: true
    paths:
    - archery/bow/*

jobs:
- name: verify-scala
  plan:
  - get: pull-request-scala
    trigger: true
    version: every
  - put: pull-request-scala
    params:
      path: pull-request-scala
      context: archery/scala
      status: pending
  - aggregate:
    - task: sbt-test
      file: pull-request-scala/ci/tasks/sbt/test.yml
      input_mapping:
        repo: pull-request-scala
      params:
        PROJECT: arrow
    - task: sbt-it-test
      file: pull-request-scala/ci/tasks/sbt/it-test.yml
      input_mapping:
        repo: pull-request-scala
      params:
        PROJECT: arrow
  on_success:
    put: pull-request-scala
    params:
      path: pull-request-scala
      context: archery/scala
      status: success
  on_failure:
    put: pull-request-scala
    params:
      path: pull-request-scala
      context: archery/scala
      status: failure
- name: verify-python
  plan:
  - get: pull-request-python
    trigger: true
    version: every
  - put: pull-request-python
    params:
      path: pull-request-python
      context: archery/python
      status: pending
  - task: pytest
    file: pull-request-python/ci/tasks/python/test.yml
    input_mapping:
      repo: pull-request-python
    params:
      SRC_PATH: archery/bow
  on_success:
    put: pull-request-python
    params:
      path: pull-request-python
      context: archery/python
      status: success
  on_failure:
    put: pull-request-python
    params:
      path: pull-request-python
      context: archery/python
      status: failure

