---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

params:
  DOCKERFILE_PATH: Dockerfile
  SRC_PATH: .

inputs:
- name: repo
- name: version

outputs:
- name: docker-src

run:
  path: sh
  args:
  - repo/archery/ci/tasks/docker/prepare.sh
