groups: []
resources:
- name: hawkeye-repo
  type: git
  source:
    branch: test
    private_key: ((github-private-key))
    uri: git@github.com:paufregi/hawkeye.git
resource_types: []
jobs:
- name: release
  serial: true
  plan:
  - get: hawkeye-repo
  - task: sbt
    file: hawkeye-repo/ci-tasks/sbt/sbt.yml
    params:
      SBT_COMMANDS: '"project crossbow" compile'
    input_mapping:
      repo: hawkeye-repo
