---
resources:
- name: hawkeye-repo
  type: git
  source:
    uri: git@github.com:paufregi/hawkeye.git
    private_key: ((github-private-key))
    check_every: 30s

jobs:
- name: compile
  serial: true
  plan:
    - get: hawkeye-repo
    - task: build
      file: hawkeye-repo/ci/tasks/compile.yml
